//MainWindow Component Constructor
module.exports = (function() {
	return {
			'webview': {
					backgroundColor: '#fff',
					top: '0%',
					bottom: '48dp',
				},
			'status': {
					top: '5dp',
					right: '30dp',
					width: '64dp',
					height: '20dp',
					backgroundColor: '#8000',
					borderRadius: 10,
					color : '#fff',
					backgroundSelectedColor: '#fff',
					textAlign: 'center',
				},
			'pin-status': {
					top: '5dp',
					right: '5dp',
					width: '20dp',
					height: '20dp',
					backgroundColor: '#8000',
					borderRadius: 10,
					color : '#fff',
					backgroundSelectedColor: '#fff',
				},
			'console': {
					backgroundColor: '#6000',
					top: '35dp',
					left: '10dp',
					right: '50dp',
					bottom: '58dp',
					borderRadius: 10,
					color : '#fff',
					backgroundSelectedColor: '#0000',
					textAlign: 'left',
				},
			'toolbar': {
					height: '48dp',
					bottom: 0,
					backgroundColor:'#356',
				},
			'toolbar-button-inner': {
					height:'32dp',
					width: '32dp',
				},
			'toolbar-like-button': {
					left:  '0dp',
					top:   '0dp',
					height:'100%',
					width: '20%',
					borderRadius: 15,
					backgroundSelectedColor: '#ccc',
				},
			'toolbar-reblog-button': {
					left:  '20%',
					top:   '0dp',
					height:'100%',
					width: '20%',
					borderRadius: 15,
					backgroundSelectedColor: '#ccc',
				},
			'toolbar-prev-button': {
					left:  '40%',
					top:   '0dp',
					height:'100%',
					width: '20%',
					borderRadius: 15,
					backgroundSelectedColor: '#ccc',
				},
			'toolbar-next-button': {
					left:  '60%',
					top:   '0dp',
					height:'100%',
					width: '20%',
					borderRadius: 15,
					backgroundSelectedColor: '#ccc',
				},
			'toolbar-pin-button': {
					left:  '80%',
					top:   '0dp',
					height:'100%',
					width: '20%',
					borderRadius: 15,
					backgroundSelectedColor: '#ccc',
				},
			'toolbar-pin-badge': {
					right:  '2dp',
					top:   '2dp',
					height:'20dp',
					width: '48dp',
					backgroundColor: 'red',
					borderRadius: 10,
					color: '#fff',
					textAlign: 'center',
				}
		};
})();
